# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
stages: 
- stage: CI
  displayName: Integração Contínua
  jobs:
  - job: Construção da imagem docker
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'fabricioveronez/rotten-potatoes'
        command: 'buildAndPush'
        Dockerfile: 'src/Dockerfile'
        buildContext: 'src'
        tags: |
          $(Build.BuildId)
          latest

- stage: CD
  displayName: Pipeline de entrega continua
  dependsOn: CI
  jobs:
  - job: Deploy
    displayName: Deploy no Kubernetes
    steps:  
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'k8s-default-1646655554647'
        namespace: 'default'
        manifests: 'k8s/*'
        containers: 'fabricioveronez/live-conversao-temperatura:$(Build.BuildId)'



