# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
stages: 
- stage: CI
  displayName: Integração Contínua
  jobs:
  - job: Docker
    steps:
    - task: Docker@2
      displayName: Construção da imagem Docker
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'fabricioveronez/rotten-potatoes'
        command: 'buildAndPush'
        Dockerfile: 'src/Dockerfile'
        buildContext: 'src'
        tags: |
          $(Build.BuildId)
          latest

- stage: CD
  displayName: Pipeline de entrega continua
  dependsOn: CI
  jobs:
  - job: Deploy
    steps:  
    - task: KubernetesManifest@1
      displayName: Deploy no Kubernetes
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'Kubernetes Vivo'
        manifests: 'k8s/deployment.yaml'
        containers: 'fabricioveronez/rotten-potatoes:$(Build.BuildId)'